
import React from 'react';
import { 
  Play, 
  Edit3, 
  Trophy, 
  Newspaper, 
  Users, 
  Home, 
  Settings, 
  BarChart3, 
  LayoutGrid, 
  Database, 
  GripVertical, 
  Info, 
  PlusCircle, 
  ArrowRightLeft, 
  Repeat, 
  MinusCircle, 
  TrendingUp, 
  TrendingDown, 
  Bot, 
  RefreshCw, 
  Pause, 
  X, 
  Check, 
  User, 
  Gavel, 
  Calendar, 
  Target, 
  Award, 
  Plus, 
  Search, 
  ChevronRight, 
  FileText,
  Coins,
  MapPin,
  Cloud,
  Star,
  LogOut,
  BarChart2,
  Zap,
  Globe
} from 'lucide-react';

export const Icons = {
  PlayMatch: (props: any) => <Play className={props.className || "h-7 w-7"} {...props} />,
  Editor: (props: any) => <Edit3 className={props.className || "h-7 w-7"} {...props} />,
  Leagues: (props: any) => <Trophy className={props.className || "h-7 w-7"} {...props} />,
  News: (props: any) => <Newspaper className={props.className || "h-7 w-7"} {...props} />,
  Newspaper: (props: any) => <Newspaper className={props.className || "h-7 w-7"} {...props} />,
  Lineups: (props: any) => <Users className={props.className || "h-7 w-7"} {...props} />,
  Home: (props: any) => <Home {...props} />,
  Settings: (props: any) => <Settings {...props} />,
  Trophy: (props: any) => <Trophy {...props} />,
  Podium: (props: any) => <BarChart3 {...props} />,
  ChartPie: (props: any) => <LayoutGrid {...props} />,
  Database: (props: any) => <Database {...props} />,
  DragHandle: (props: any) => <GripVertical className={props.className || "h-5 w-5"} {...props} />,
  Info: (props: any) => <Info className={props.className || "h-4 w-4"} {...props} />,
  PlusCircle: (props: any) => <PlusCircle className={props.className || "h-6 w-6"} {...props} />,
  Transfers: (props: any) => <ArrowRightLeft className={props.className || "h-7 w-7"} {...props} />,
  Compare: (props: any) => <Repeat className={props.className || "h-7 w-7"} {...props} />,
  RemoveCircle: (props: any) => <MinusCircle className={props.className || "h-6 w-6"} {...props} />,
  TrendingUp: (props: any) => <TrendingUp className={props.className || "h-6 w-6"} {...props} />,
  TrendingDown: (props: any) => <TrendingDown className={props.className || "h-6 w-6"} {...props} />,
  Bot: (props: any) => <Bot className={props.className || "h-7 w-7"} {...props} />,
  Play: (props: any) => <Play className={props.className || "h-6 w-6"} {...props} />,
  RefreshCw: (props: any) => <RefreshCw className={props.className || "h-6 w-6"} {...props} />,
  Pause: (props: any) => <Pause className={props.className || "h-6 w-6"} {...props} />,
  X: (props: any) => <X className={props.className || "h-6 w-6"} {...props} />,
  Check: (props: any) => <Check className={props.className || "h-6 w-6"} {...props} />,
  User: (props: any) => <User className={props.className || "h-6 w-6"} {...props} />,
  Users: (props: any) => <Users className={props.className || "h-6 w-6"} {...props} />,
  Gavel: (props: any) => <Gavel className={props.className || "h-6 w-6"} {...props} />,
  Schedule: (props: any) => <Calendar className={props.className || "h-7 w-7"} {...props} />,
  Strategy: (props: any) => <Target className={props.className || "h-6 w-6"} {...props} />,
  Award: (props: any) => <Award className={props.className || "h-6 w-6"} {...props} />,
  Plus: (props: any) => <Plus className={props.className || "h-6 w-6"} {...props} />,
  Search: (props: any) => <Search className={props.className || "h-6 w-6"} {...props} />,
  ChevronRight: (props: any) => <ChevronRight className={props.className || "h-6 w-6"} {...props} />,
  Calendar: (props: any) => <Calendar className={props.className || "h-6 w-6"} {...props} />,
  FileText: (props: any) => <FileText className={props.className || "h-6 w-6"} {...props} />,
  ArrowRightLeft: (props: any) => <ArrowRightLeft className={props.className || "h-6 w-6"} {...props} />,
  Coins: (props: any) => <Coins className={props.className || "h-6 w-6"} {...props} />,
  MapPin: (props: any) => <MapPin className={props.className || "h-6 w-6"} {...props} />,
  Cloud: (props: any) => <Cloud className={props.className || "h-6 w-6"} {...props} />,
  Star: (props: any) => <Star className={props.className || "h-6 w-6"} {...props} />,
  LogOut: (props: any) => <LogOut className={props.className || "h-6 w-6"} {...props} />,
  BarChart2: (props: any) => <BarChart2 className={props.className || "h-6 w-6"} {...props} />,
  Zap: (props: any) => <Zap className={props.className || "h-6 w-6"} {...props} />,
  Target: (props: any) => <Target className={props.className || "h-6 w-6"} {...props} />,
  Globe: (props: any) => <Globe className={props.className || "h-6 w-6"} {...props} />,
};

